<a href="https://colab.research.google.com/github/wilsonalffa/Ciencia-de-dados/blob/main/AulaPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalação do Pandas

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import numpy as np
print (pd.__version__)
print (np.__version__)

2.2.2
2.0.2

## Series
- https://pandas.pydata.org/docs/reference/series.html

In [4]:

serie_dados=pd.Series([10,20,30,40,50])
print(serie_dados)
type(serie_dados)

0    10
1    20
2    30
3    40
4    50
dtype: int64

pandas.core.series.Series

In [5]:
array_inteiros = [10,20,30,40,50]
Indices = ['A', 'B', 'C', 'D', 'E']
serie_dados=pd.Series(array_inteiros, index=Indices)
print(serie_dados)
#

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [6]:
np_array_inteiros = np.array([10,20,30,40,50])
print(np_array_inteiros)
type(np_array_inteiros)
#

[10 20 30 40 50]

numpy.ndarray

In [7]:
serie_dados.shape

(5,)

In [8]:
serie_dados.ndim

1

In [9]:
serie_dados.size

5

In [12]:
serie_dados.index = ['Carro', 'Moto', 'Avião', 'Barco', 'Moto Nautica']
serie_dados

Carro           10
Moto            20
Avião           30
Barco           40
Moto Nautica    50
dtype: int64

In [13]:
valores = np.random.rand(10)
index = np.arange(0,10)
print(valores)
print(index)
type(valores), type(index)

[0.93237502 0.20718374 0.13933654 0.66528413 0.69933688 0.91752148
 0.78961839 0.98813131 0.82244706 0.09105542]
[0 1 2 3 4 5 6 7 8 9]

(numpy.ndarray, numpy.ndarray)

In [14]:
serie_dados = pd.Series(valores, index)
print(serie_dados)

0    0.932375
1    0.207184
2    0.139337
3    0.665284
4    0.699337
5    0.917521
6    0.789618
7    0.988131
8    0.822447
9    0.091055
dtype: float64

In [15]:
dicionario = {'João':10, 'Alice':5, 'Gustavo':6, 'Pedro':9 }
print(dicionario)

{'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}

In [16]:
dic_serie_dados = pd.Series(dicionario)
print(dic_serie_dados)

João       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [17]:
serie_dados[:]

0    0.932375
1    0.207184
2    0.139337
3    0.665284
4    0.699337
5    0.917521
6    0.789618
7    0.988131
8    0.822447
9    0.091055
dtype: float64

In [18]:
serie_dados[0:3]

0    0.932375
1    0.207184
2    0.139337
dtype: float64

In [19]:
serie_dados[-1:]

9    0.091055
dtype: float64

In [20]:
serie_dados[0:-1]

0    0.932375
1    0.207184
2    0.139337
3    0.665284
4    0.699337
5    0.917521
6    0.789618
7    0.988131
8    0.822447
dtype: float64

In [21]:
s2 = serie_dados[0:3]
print(s2)

0    0.932375
1    0.207184
2    0.139337
dtype: float64

In [24]:
serie_dados2 = serie_dados
serie_dados2[0] = 10
print(serie_dados2[0])
print(serie_dados[0])

10.0
10.0

In [25]:
serie_dados2 = serie_dados.copy()
serie_dados2[0] = 20
print(serie_dados2[0])
print(serie_dados[0])

20.0
10.0